name: Container Image CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Anchore Container Scan
        uses: anchore/scan-action@v3.3.5
        with:
          path: "/ZayanShahid/flask_tutorial"
          fail-build: false
